### ISSUE TITLE
Pre trained model ?

### ISSUE THREAD

**Issue by raghavgurbaxani** [ishin-pie/east-mobilenet#1]
hi 

thank you for your great work. Is is possible to share the trained pytorch model ? Thanks ..

**Comment by ishin-pie** [comment]
Hi, the trained model is included in this repository, named [model_best.pth.tar](https://github.com/ishin-pie/east-mobilenet/blob/master/model_best.pth.tar)

**Comment by raghavgurbaxani** [comment]
thanks @ishin-pie , I found it. Can you share what was the accuracy you achieved using this trained model ?

**Comment by ishin-pie** [comment]
> thanks @ishin-pie , I found it. Can you share what was the accuracy you achieved using this trained model ?

I got Hmean = 47.26% (ICDAR 2015 test-set)
